### ISSUE TITLE
Empty map view

### ISSUE THREAD

**Issue by ohnewein** [noi-techpark/bz-parking-angular#1] opened 2017-11-28 14:59 UTC
There are no points visualized on the map view. Maybe because I did not allow to use my current position? The points of park houses should be visualized independently from the user choice to give his current position.

![screenshot from 2017-11-28 15-55-49](https://user-images.githubusercontent.com/414797/33326355-049c117c-d455-11e7-94ca-8c801c4b1409.png)

**Comment by bertolla** [comment] 2017-11-29 13:26
Since the page is in SSL every resource that it uses, needs to be ssl.
I also use our inhouse geoserver, which runs under the domain geodata.integreen-life.bz.it
The problem is that nobody ever set it up with ssl and did not buy a certificate for it.
What i now did as a short term solution to solve the problem, is to make ipchannels.integreen-life.bz.it/geoserver (which has a SSL Certificate) point to our geoserver and tell the app to use that endpoint.
Might not be the best solution but it works for now.
2 other things can be done:
- move the Domain integreen-life.bz.it to route53 and manager the subdomains with free aws ssl-certificates
- request our IT-Department to buy a certificate for geodata.integreen-life.bz.it

**Comment by ohnewein** [comment] 2017-12-03 23:14
Does this solve this issue?

**Comment by bertolla** [comment] 2017-12-11 16:41
> a short term solution
Like i said, but I think by moving the apache config on our frontend server this solution can also be fixed by using a loadbalancer with a free aws certificate, so the it-department will still be able  to have control of the domain. For the current state this might be the best solution

**Closed as completed** 2018-01-26 09:52 UTC
Labels: bug
